version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - npm install -g aws-cdk
      - npm install -g typescript
      - cdk --version

  build:
    commands:
      - export STACK_NAME=${CODEBUILD_WEBHOOK_HEAD_REF}
      - echo Deploy started on `date`
      - echo Build CDK project...
      - npm install
      - cdk deploy --require-approval never
      - echo Deploy completed on the `date`