version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - npm install -g aws-cdk
      - npm install -g typescript
      - cdk --version

  # pre_build:
  #   commands:
  #     - echo Logging in to Amazon ECR...
  #     - aws --version
  #     - echo $AWS_DEFAULT_REGION
  #     # - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
  #     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  #     - IMAGE_TAG=${COMMIT_HASH:=latest}

  build:
    commands:
      - echo Deploy started on `date`
      - echo Build CDK project...
      - npm install
      - cdk deploy --require-approval never
      - echo Deploy completed on the `date`