version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 12
    commands:
      - npm install -g aws-cdk
      - npm install -g typescript
      - cdk --version

  build:
    commands:
      - echo Deploy started on `date`
      - echo Build CDK project...
      - npm install
      - $STACK_NAME=build_stack_master
      - cdk deploy --require-approval never
      - echo Deploy completed on the `date`